version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8443:8443"
    volumes:
      - .:/app
      - /app/tmp  # Exclude tmp directory from sync
    secrets:
      - internal_api_key
      - gouda_ip
    environment:
      - CGO_ENABLED=0
      - DATABASE_URL=postgres://postgres:postgres@db:5432/guac?sslmode=disable
      - INTERNAL_API_KEY_FILE=/run/secrets/internal_api_key
      - GOUDA_IP_FILE=/run/secrets/gouda_ip
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: guac
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guac
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

secrets:
  internal_api_key:
    file: ./secrets/internal_api_key
  gouda_ip:
    file: ./secrets/gouda_ip
